# Generated by Django 5.2.3 on 2025-07-25 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmbcChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustingTube', models.CharField(max_length=100)),
                ('cylinderBody', models.CharField(max_length=100)),
                ('pistonTrunnion', models.CharField(max_length=100)),
                ('plungerSpring', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axleGuide', models.CharField(max_length=100)),
                ('bogieFrameCondition', models.CharField(max_length=100)),
                ('bolster', models.CharField(max_length=100)),
                ('bolsterSuspensionBracket', models.CharField(max_length=100)),
                ('lowerSpringSeat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogieNo', models.CharField(max_length=20)),
                ('dateOfIOH', models.DateField()),
                ('deficitComponents', models.TextField()),
                ('incomingDivAndDate', models.CharField(max_length=100)),
                ('makerYearBuilt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WheelFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condemningDia', models.CharField(max_length=50)),
                ('lastShopIssueSize', models.CharField(max_length=50)),
                ('treadDiameterNew', models.CharField(max_length=50)),
                ('wheelGauge', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BogieChecksheetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=50, unique=True)),
                ('inspectionBy', models.CharField(max_length=100)),
                ('inspectionDate', models.DateField()),
                ('bmbcChecksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.bmbcchecksheet')),
                ('bogieChecksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.bogiechecksheet')),
                ('bogieDetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.bogiedetails')),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecificationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=50, unique=True)),
                ('submittedBy', models.CharField(max_length=100)),
                ('submittedDate', models.DateField()),
                ('fields', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.wheelfields')),
            ],
        ),
    ]
